on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - master
jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Fetch recent GitHub activity
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        # Get user profile info - try authenticated first, then public
        if ! gh api user > user_profile.json 2>/dev/null; then
          gh api users/nguyenvanduocit > user_profile.json
        fi
        
        # Get recent repositories - try authenticated first, then public
        if ! gh api user/repos --field sort=updated --field per_page=10 > recent_repos.json 2>/dev/null; then
          gh api users/nguyenvanduocit/repos --field sort=updated --field per_page=10 > recent_repos.json
        fi
        
        # Get recent public events using the correct public endpoint
        gh api users/nguyenvanduocit/events/public --field per_page=30 > recent_activity.json

    - name: Install Cursor CLI
      run: |
        curl https://cursor.com/install -fsS | bash
        echo "$HOME/.cursor/bin" >> $GITHUB_PATH

    - name: Generate README with AI
      env:
        CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
      run: |
        cursor-agent -p "You are in a GitHub action. I want you to analyze my recent GitHub activity and create a personalized README.md file for my profile.

        Please:
        1. Read the @user_profile.json, @recent_activity.json, and @recent_repos.json files to understand my GitHub activity
        2. Read the current @README.md file to see what's there now
        3. Create a new README.md file that introduces who I am based on my activity patterns
        4. Highlight what I'm currently working on (based on recent commits/repos)
        5. Show my areas of focus and expertise
        6. Maintain a professional yet personal tone
        7. Include relevant information that tells people about my current projects and interests

        Format it as a proper GitHub profile README with markdown formatting. Keep it concise but informative.

        Create the README.md file directly. Don't expose secrets or sensitive information. then commit and push the README.md to repository, use gh cli" --force --model gpt-5