on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.TOKEN }}
        
    - name: Fetch GitHub activity
      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
      run: |
        # Get user profile info with error handling
        if ! gh api user > user_profile.json 2>/dev/null; then
          echo "Failed to fetch user profile, creating minimal profile"
          echo '{"login":"'$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)'","name":"Developer","bio":"Building things on GitHub"}' > user_profile.json
        fi
        
        # Get recent repositories with error handling
        if ! gh api user/repos --field sort=updated --field per_page=10 > recent_repos.json 2>/dev/null; then
          echo "Failed to fetch repos, using empty array"
          echo '[]' > recent_repos.json
        fi
        
        # Get recent events with simplified approach
        if ! gh api users/$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)/events/public --field per_page=30 > recent_activity.json 2>/dev/null; then
          echo "Failed to fetch events, using empty array"
          echo '[]' > recent_activity.json
        fi

    - name: Generate README
      run: |
        # Create a simple README based on available data
        cat > README.md << 'EOF'
        # Hi there! 👋
        
        I'm $(jq -r '.name // .login' user_profile.json), a developer passionate about building things.
        
        ## 🔭 Recent Activity
        
        $(if [ -s recent_repos.json ] && [ "$(jq length recent_repos.json)" -gt 0 ]; then
          echo "### Recent Repositories"
          jq -r '.[:5] | .[] | "- **" + .name + "**: " + (.description // "No description")' recent_repos.json
        else
          echo "Working on various projects and contributions!"
        fi)
        
        ## 📫 Get in touch
        
        $(jq -r '.bio // "Always learning and building new things!"' user_profile.json)
        
        ---
        *This README is automatically updated based on my GitHub activity*
        EOF

    - name: Commit and push changes
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        
        if [[ "$(git status --porcelain)" != "" ]]; then
          git add README.md
          git commit -m "🤖 Auto-update README based on recent GitHub activity"
          git push
        else
          echo "No changes to commit"
        fi
        
        # Cleanup temporary files
        rm -f recent_activity.json recent_repos.json user_profile.json
