on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - master
jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Fetch recent GitHub activity
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching user profile..."
        gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /users/nguyenvanduocit > user_profile.json || echo '{"login":"nguyenvanduocit","name":"Developer"}' > user_profile.json
        
        echo "Fetching repositories..."
        gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/users/nguyenvanduocit/repos?per_page=10&sort=updated" > recent_repos.json || echo '[]' > recent_repos.json
        
        echo "Fetching public events..."
        gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/users/nguyenvanduocit/events/public?per_page=30" > recent_activity.json || echo '[]' > recent_activity.json
        
        echo "Data fetching complete. File sizes:"
        ls -la *.json

    - name: Install Cursor CLI
      run: |
        curl https://cursor.com/install -fsS | bash
        echo "$HOME/.cursor/bin" >> $GITHUB_PATH

    - name: Generate README with AI
      env:
        CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cursor-agent -p "You are running inside a GitHub Actions runner (ubuntu-latest). The GitHub CLI (gh) is available and authenticated, so you can use gh to perform GitHub operations as needed.

        I want you to analyze my recent GitHub activity and create a personalized README.md file for my profile.

        Please:
        1. Read the @user_profile.json, @recent_activity.json, and @recent_repos.json files to understand my GitHub activity
        2. Read the current @README.md file to see what's there now
        3. Create a new README.md file that introduces who I am based on my activity patterns (never talk about all-in-one-model-context-protocol, dev-kit, they are replaced by multiple mcp repos)
        4. Highlight what I'm currently working on (based on recent commits/repos)
        5. Show my areas of focus and expertise
        6. Maintain a professional yet personal tone
        7. Include relevant information that tells people about my current projects and interests

        Format it as a proper GitHub profile README with markdown formatting. Keep it concise but informative.

        After generating, stage, commit, and push the README.md file to this repository (use git for commit/push). For GitHub operations (e.g., querying APIs, creating PRs), the gh CLI is available and authenticated. Do not expose secrets or any sensitive information." --force --model gpt-5
